# Generated by Django 2.1.5 on 2019-02-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TweetDetails',
            fields=[
                ('id_str', models.CharField(default='', max_length=512, primary_key=True, serialize=False)),
                ('text', models.CharField(default='', max_length=512)),
                ('created_at', models.CharField(default='', max_length=512)),
            ],
        ),
    ]
