# Generated by Django 2.1.5 on 2019-02-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20190222_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetdetails',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tweetdetails',
            name='retweets',
            field=models.IntegerField(default=0),
        ),
    ]
