# Generated by Django 2.1.5 on 2019-02-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_auto_20190222_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetdetails',
            name='created_by',
            field=models.CharField(default='', max_length=512),
        ),
    ]
