# Generated by Django 2.1.5 on 2019-02-23 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_remove_tweetdetails_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweetdetails',
            old_name='user',
            new_name='user_id_str',
        ),
    ]
