# Generated by Django 2.1.5 on 2019-02-23 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_tweetdetails_posted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetdetails',
            name='posted_by',
        ),
    ]
