# Generated by Django 2.1.5 on 2019-02-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_remove_tweetdetails_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetdetails',
            name='posted_by',
            field=models.CharField(default='', max_length=512),
        ),
    ]
