# Generated by Django 2.1.5 on 2019-02-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_tweetdetails_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetdetails',
            name='in_reply_to',
            field=models.CharField(default='', max_length=512),
        ),
    ]
