# Generated by Django 2.1.5 on 2019-02-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_remove_tweetdetails_in_reply_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('tweetid', models.CharField(default='', max_length=512, primary_key=True, serialize=False)),
                ('tweet_likes', models.IntegerField(default=0)),
                ('tweet_retweets', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TweetReplies',
            fields=[
                ('tweet_id_str', models.CharField(default='', max_length=512, primary_key=True, serialize=False)),
                ('tweet_text', models.CharField(default='', max_length=512)),
                ('reply_id_str', models.CharField(default='', max_length=512)),
                ('user_posted', models.CharField(default='', max_length=512)),
            ],
        ),
    ]
