# Generated by Django 2.1.5 on 2019-02-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0013_reaction_tweetreplies'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='auto_increment_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reaction',
            name='tweetid',
            field=models.CharField(default='', max_length=512),
        ),
    ]
