# Generated by Django 2.1.7 on 2019-02-25 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0015_reaction_time_and_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='time_and_date',
        ),
    ]
