# Generated by Django 2.1.7 on 2019-02-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0016_remove_reaction_time_and_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='time_and_date',
            field=models.CharField(default='', max_length=512),
        ),
    ]
