# Generated by Django 2.1.7 on 2019-02-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0018_remove_reaction_time_and_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reaction',
            name='created_at',
            field=models.CharField(default='', max_length=512),
        ),
    ]
