# Generated by Django 2.1.7 on 2019-02-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0019_auto_20190227_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetreplies',
            name='created_at',
            field=models.CharField(default='', max_length=512),
        ),
    ]
