# Generated by Django 2.1.7 on 2019-02-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0020_tweetreplies_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetreplies',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
