# Generated by Django 2.1.7 on 2019-02-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0022_auto_20190228_0952'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetails',
        ),
        migrations.AddField(
            model_name='tweetdetails',
            name='followers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tweetdetails',
            name='screen_name',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='tweetdetails',
            name='userid',
            field=models.CharField(default='', max_length=512),
        ),
    ]
