# Generated by Django 2.1.7 on 2019-02-28 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0024_remove_tweetdetails_screen_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweetdetails',
            old_name='user_id_str',
            new_name='username',
        ),
    ]
