# Generated by Django 2.1.7 on 2019-02-28 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0025_auto_20190228_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweetdetails',
            old_name='username',
            new_name='user_id_str',
        ),
    ]
