# Generated by Django 2.1.7 on 2019-02-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0026_auto_20190228_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetreplies',
            name='sentiment_value',
        ),
        migrations.AddField(
            model_name='tweetdetails',
            name='sentiment_value',
            field=models.IntegerField(default=0),
        ),
    ]
