# Generated by Django 2.1.5 on 2019-02-28 11:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0027_auto_20190228_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetdetails',
            name='sentiment_value',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=20),
        ),
    ]
