# Generated by Django 2.1.5 on 2019-03-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0029_tweetdetails_first_saved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streaming',
            fields=[
                ('id_str', models.CharField(default='', max_length=512, primary_key=True, serialize=False)),
                ('text', models.CharField(default='', max_length=512)),
                ('created_at', models.CharField(default='', max_length=512)),
            ],
        ),
    ]
