# Generated by Django 2.1.5 on 2019-03-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0030_streaming'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='sentiment_value',
        ),
        migrations.AddField(
            model_name='reaction',
            name='number_of_followers',
            field=models.IntegerField(default=0),
        ),
    ]
