# Generated by Django 2.1.5 on 2019-03-03 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0031_auto_20190303_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetreplies',
            name='created',
        ),
    ]
