# Generated by Django 2.1.5 on 2019-03-03 09:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0032_remove_tweetreplies_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetreplies',
            name='reply_sentiment',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=20),
        ),
    ]
