# Generated by Django 2.1.5 on 2019-03-03 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0033_tweetreplies_reply_sentiment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetdetails',
            name='first_saved',
        ),
    ]
