# Generated by Django 2.1.5 on 2019-03-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0034_remove_tweetdetails_first_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetdetails',
            name='first_saved',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
