# Generated by Django 2.1.5 on 2019-03-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0035_tweetdetails_first_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='first_saved',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tweetreplies',
            name='first_saved',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
