# Generated by Django 2.1.5 on 2019-03-04 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0036_auto_20190304_0957'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Streaming',
        ),
    ]
