# Generated by Django 2.1.5 on 2019-03-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0037_delete_streaming'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('tweetidstr', models.CharField(default='', max_length=512, primary_key=True, serialize=False)),
                ('tweet_text', models.CharField(default='', max_length=512)),
                ('user_posted', models.CharField(default='', max_length=512)),
            ],
        ),
    ]
