# Generated by Django 2.1.5 on 2019-03-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0039_auto_20190306_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='user_id_str',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='tweetreplies',
            name='user_id_str',
            field=models.CharField(default='', max_length=512),
        ),
    ]
