# Generated by Django 2.1.5 on 2019-03-08 15:55

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysis', '0040_auto_20190307_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saved',
            fields=[
                ('id_str', models.CharField(default='', max_length=512, primary_key=True, serialize=False)),
                ('text', models.CharField(default='', max_length=512)),
                ('created_at', models.CharField(default='', max_length=512)),
                ('likes', models.IntegerField(default=0)),
                ('retweets', models.IntegerField(default=0)),
                ('posted_by', models.CharField(default='', max_length=512)),
                ('userid', models.CharField(default='', max_length=512)),
                ('followers_count', models.IntegerField(default=0)),
                ('sentiment_value', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=20)),
                ('first_saved', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_id_str', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='TweetReplies',
        ),
    ]
